version: '2.0'
services:
  climbing_client:
    container_name: climbing_client
    build: client
    expose:
      - 80
  climbing_server:
    container_name: climbing_server
    build: server
    environment:
      - ENVIRONMENT="production"
    expose:
      - 3500
  climbing-reverse-proxy:
    build: proxy
    depends_on:
      - climbing_client
      - climbing_server
