version: '2.0'
services:
  climbing_client:
    container_name: climbing_client
    build: client
    expose:
      - 80
  climbing_server:
    container_name: climbing_server
    build: server
    environment:
      - ENVIRONMENT=production
      - UPLOAD_KEY=your_upload_key_here
    expose:
      - 80
  climbing_reverse_proxy:
    container_name: climbing_reverse_proxy
    build: proxy
    depends_on:
      - climbing_client
      - climbing_server
